name: build scrinvex sif

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install Apptainer
        run: |
          sudo apt-get update
          sudo apt-get install -y apptainer

      - name: Pull scrinvex
        run: |
          apptainer pull scrinvex.sif docker://gcr.io/broad-cga-aarong-gtex/scrinvex

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: scrinvex-sif
          path: scrinvex.sif
